version: '3'
services:
  mongo:
    container_name: mongodb-container
    image: mongo:6.0.12
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-survey-container
    build: .
    restart: always
    image: survey-api
    command: npm start
    volumes:
      - ./dist:/usr/src/node-api-survey/dist
    ports:
      - "5050:5050"
    links:
      - mongo